### ISSUE TITLE
Your long-term pov  

### ISSUE THREAD

**Issue by pascalandy** [swarmstack/swarmstack#12]
Hello Mike,

First, thank you for building such a great stack. I’m following your updates carefully and when I read your release notes I’m like “Hell yeah, this man got it”. 

We can see the latest release is at 0.9.9. My questions are:

- Do you have a public roadmap? (or what’s in your ToDo)
- Are you gonna publish v1.0.0 soon?
- Do you plan to use Traefik in your stack?

If you are curious here is a bit about my stack.

I run Swarm for about 18 months. I love it and I feel it’s time to go a for a much more solid intra-as-code setup (something like your). I manage static websites and CMS apps. At the moment I run around 70 services.

My OS is Ubuntu and I’m still not sure if it’s worth the pain to move from Ubuntu to CentOS in order to go all in and build around swarmstack. (I guess you have no intention to maintain a stack for Ubuntu but who knows.)

Would you share how you position yourself and your project? I want to make sure about how you see things in the long run before making such a commitment.

I don’t expect a quick answer in any case, but at least you know that, as a potential user, how I fell :-p

Cheers!
Pascal

**Comment by mh720** [comment]
Hi Pascal,

Thanks for asking. I've been meaning to write up a road-map and let folks know what the immediate plans are. The Plan is to reach 1.0 shortly (weeks) with some additional cloud vendor testing, vendor updates, and with only the addition of a small script that can be used to pick up user changes from an old swarmstack installation directory (even on an old host) into a freshly cloned swarmstack of the latest version, as a way to more cleanly upgrade swarmstack to newer versions after 1.0. Right now, you have to bring your changes along if you clone the latest swarmstack version.

After 1.0, any changes will likely be small ones unless the community decides that this base deployment needs additional tools. Early next year I plan to work on an Elasticsearch / Fluentd / Kibana EFK stack as a separate project in https://github.com/swarmstack to complement the DevOps tools already available there - I've tried to make all of the projects useful on their own merits (such as the errbot docker container), but also easily integrated for swarmstack users. I personally might also work on a CI/CD stack that could also integrate with swarmstack monitoring and using the Portainer webhooks for deployment.

I know that there is a good amount of community interest in using Traefik or other proxies. My hope is that someone with Traefik experience will help out with some PRs to the swarmstack.yml ansible playbook that could make Traefik an option defined in the ansible cluster file. swarmstack maintains a build of Caddy which follows their open-source releases. The default Caddy image used by swarmstack disables telemetry reporting.

Since the Docker compose stack can be used on any Docker swarm cluster satisfying the requirements, it can be used on Ubuntu today. The additional work to swarmstack to support installation of ETCD/PORTWORX/DOCKER on other OS distributions should just be some additions to the existing ansible playbooks to be aware of which distro they are being run on and do the right things in those cases, ansible makes that quite easy actually. Mainly the bits around yum (and maybe systemd) would need to change for Ubuntu. I've opened a project within swarmstack to add support to additional distro  targets, and I'm hoping for community help from experts in these other systems to help fill in the gaps there, while I can use ubuntu with the best of them, EL has my own enterprise expertise behind it.

In the long-run, I see this particular project receiving mainly poilsh and vendor updates, and additional complementary projects that are easily integrated. I'm keeping in mind small fresh development teams being able to easily deploy the base swarmstack tools and have a monitored and HA Docker platform to develop and eventually enter production with. This stack is used by developers in enterprise environments as well, and does receive some testing and bug fixes based around enterprise needs as well.

**Comment by pascalandy** [comment]
Thank you for your kind answers.
I really like what you just shared here. Let me share some thoughts.

### EFK
For the EFK (I used the hear ELK), it’s not something I see value at the moment, but I guess my requirements are not enterprise level at this point. The whole monitoring tools you put together is more than enough for me. :)

### CI/CD
I use Travis for my [main project](https://travis-ci.org/firepress-org/ghostfire/branches). I plan to use GitLab workers in the future in order to CICD all those smaller projects as well.

I understand you actually want to monitor the performance of the CI/CD set up? 

A build takes less than 3 minutes, and all unit tests make me happy. I'll be curious to see what you have in mind about the monitoring aspect of a CI/CD.

### Traefik
Traefik is at the core of my stack. I know it well. I built a simple stack to help people to start their stack around it. [Check it out](https://github.com/pascalandy/docker-stack-this/tree/master/traefik_stack5). Using play-with-docker, you will see it live within 45 seconds.

I can surely help here but I never seriously worked with Ansible. It seems to look like a Travis yaml file, but I’m not sure. (I actually paid a freelancer to do this from my bash scripts but it was never stable).

To be clear, Ansible (and the nodes/docker updates in rotation you did) is a big feature the drives me into your project.

### Stateful ETCD/PORTWORX
This is the main piece I’d never been able to figure out by myself.

I won’t try to do it adapt it for ansible, on my own, for Ubuntu. But I’ll be very happy to test it if you are looking for help.

### Additional Distros:
This is a big one. As I mentioned, my stack runs on Ubuntu 16.04 for 18 months. I guess you would need to structure the project to separate Centos and other distros. Which one ??

### Cloud Vendors
I think for the “small fresh development teams” (which is me I guess), I’m clearly thinking about moving to DigitalOcean and using their block storage along rex-ray or Portwork. 

Question: Why bother sharing the second drive of each node with the Portwork setup? What happens when all three nodes go down?

### Inspiration
Might you know this [Docker capitain](https://github.com/BretFisher)? He is starting a [Docker Swarm cluster stack](https://github.com/BretFisher/dogvscat) as well. 

The nodes are created via docker-machine on DigitalOcean within one script. I think this is a massive plus over your project — no need to use the GUI to create nodes.

Anyways, I don’t want to push too far my point of view here. I’m just like a kid on Christmas Day. A bit too excited I guess.
  
Have a nice one!
Pascal

**Comment by mh720** [comment]
Hi Pascal, good info, I’ll be reading up on some of the links you sent over the winter break. ELK vs EFK is just replacing the ingesting mechanism Logstash with Fluentd, which is seems slightly more performant and doesn’t rely on java. 

Not every team needs logging capabilities, which is a separate need from monitoring and alerting. With smaller applications with less micro services, examining individual container log files might be enough for a small application, but once your services get larger, or you want to track a call through every microservice by attaching a token to logs, then you enter the realm of needing log storage and aggregatation and the ability to search across a lot of logs. Grafana 6.0 throws their hat into the ring with Loki datasource in upcoming Grafana 6.0 - https://grafana.com/loki#about so I may instead be working on an EFL project instead :) 

Regarding easy node turn-up, swarmstack is designed to run on any platform, cloud, in-house VMs, or bare metal, and while I’d love to see some contrib for integrating swarmstack with cloud providers like digital ocean / aws / gce etc, this can also be done today using terraform or other solutions, on which swarmstack can then be deployed.

Regarding monitoring CI/CD setups, this would likely just be a Prometheus alarm if the CI/CD containers don’t come back up (or for cloud users if the service becomes unavailable for a period), as well as Grafana dashboards that can just display the status of builds, build time, etc. One of the swarmstack projects takes 25 minutes to build on Docker Hub :)
